### ISSUE TITLE
Double-click highlights whole of variable

### ISSUE THREAD

**Issue by Sogl** [atom/language-php#92]
Hi!

If I double-click on variable in PHP, than it highlights the whole of the variable.
See also:
https://discuss.atom.io/t/double-click-highlights-whole-of-variable-in-php/18625
https://github.com/atom/language-php/issues/43

As I can see, this problem is fixed (https://github.com/atom/language-php/pull/75), but for me it still present in last atom version.

Also tried to put `/\\()"\':,.;<>~!@#%^&*|+=[]{}`?-` in non word characters, but nothing changed =(

Env:
- Windows 8.1 pro
- Atom 1.0.3
- language-php 0.27.0

**Comment by kevinsawicki** [comment]
> Also tried to put /\\()"\':,.;<>~!@#%^&*|+=[]{}`?- in non word characters, but nothing changed =(

Thanks for reporting this, this was definitely a bug which will be fixed in the next Atom release.

Until the next release here is how you can workaround it, run Atom > Open Your Config and in the opened file add the following:

```coffee
".source.php":
  editor:
    nonWordCharacters: "/\\\\()\"\\':,.;<>~!@#%^&*|+=[]{}`?-$"
```

This should no longer select the `$` character when double clicking

**Comment by Sogl** [comment]
>This should no longer select the $ character when double clicking

Yep, it works. Thanks, @kevinsawicki !

**Comment by abejfehr** [comment]
@kevinsawicki This is still not present in the newest version of `language-php`. Was this forgotten?

**Comment by Sogl** [comment]
@kevinsawicki @abejfehr Confirmed, doesn't work in last Atom version.

**Comment by villermen** [comment]
Any progress on this? I am still unable to select only the name of a variable. When double-clicking on `asdf` in `$asdf`, the entire string is selected even though the dollar character `$` is considered a non-word character.

**Comment by Ben3eeE** [comment]
I have worked around this bug by adding `$` to the `nonWordCharacters` setting in the `language-php` package. It seems like any setting different than the default for the `nonWordCharacters` setting fixes the problem.

![image](https://cloud.githubusercontent.com/assets/1058982/20709718/3ee57fcc-b637-11e6-9125-8236c6b8b181.png)

**Comment by 50Wliu** [comment]
So interestingly...this behavior was changed because some people didn't like it: #43.  Can't satisfy everyone I guess 😞.

**Comment by forsvunnet** [comment]
When $ is selected as part of a variable it makes multi-selection using cmd+d and cmd+ctrl+g more tedious. Especially when refactoring variable names. The dollar sign should be part of `nonWordCharacters` by default in my opinion.

**Comment by Ben3eeE** [comment]
Thank you for opening this issue!

There was an issue where the default value displayed in the `settings-view` was not correct. This has been fixed and the setting in the `language-php` package will now display the correct default value, which does not include `$`. We have also since this report fixed an issue where adding `$` to the scoped setting was not respected.

If you want `$` to not be selected when you double click a variable in php then you can configure this by adding `$` to the `language-php` setting as described in https://github.com/atom/language-php/issues/92#issuecomment-263557774

We do not currently want to change the default value for this.

**Comment by ekazda** [comment]
Is anyone else having this problem again? I'm using Atom 1.54.0 x64 on Mac and language-php 0.44.7 and when I double-click a PHP variable the $ is not selected. I am using the default Non Word Characters ```/\()"':,.;<>~!@#%^&*|+=[]{}`?-```. I tried to upgrade my version of language-php, but it seems that the new versions have not yet been rolled into the core of Atom. I also ran my Atom in safe mode and the problem is still occurring for me.

**Comment by Socha17** [comment]
Running into the issue again like @ekazda, I want my atom to select the `$` when I double click a php variable.

**Comment by KapitanOczywisty** [comment]
@ekazda @Socha17 To quick-fix this you have to set Non Word Character globally in Editor Settings

This is what breaked this behavior https://github.com/atom/atom/pull/21487
@sadick254 I think You should add separate setting to add characters globally, not merging global with TextMate ones, for exactly that reason when one language has that character as part of name and other doesn't. Current behavior is not documented and a bit confusing.

**Comment by zmorris** [comment]
Thank you @KapitanOczywisty yours was the correct answer.

In `Atom->Preferences...->Editor->Non Word Characters` change:

```
/\()"':,.;<>~!@#$%^&*|+=[]{}`?-…
```
To:
```
/\()"':,.;<>~!@#%^&*|+=[]{}`?-…
```
**Without** the `$`

Then in `Atom->Preferences...->Packages->Language Php` change:
```
/\()"':,.;<>~!@#%^&*|+=[]{}`?-
```
To:
```
/\()"':,.;<>~!@#%^&*|+=[]{}`?-$
```
**With** the `$`

That allows you to toggle the `$` specifically for PHP.

Personally I leave `$` out of both settings so I can double-click to select the whole variable (including `$`).

I think what's happening here is that the word boundary filter is additive, so the top-level `Editor->Non Word Characters` should have as few characters as possible, so that they can be added per-language. There appears to be no way to remove a letter from a language if it's added at top level (which is how you found yourself here).

Note that this behavior likely breaks most of our assumptions of how overriding works. I'd vote for individual language settings to fully override the `Editor->Non Word Characters` string (rather than inheriting and adding characters like it does now).

So this may be an `Atom` issue, not a `language-php` issue specifically.

**Comment by KapitanOczywisty** [comment]
I'd advice interested parties to open issue in [atom](https://github.com/atom/atom) to revert https://github.com/atom/atom/pull/21487 and fix that bug in some other way. In this closed issue, there is a little to no chance to get any attention from atom team.

**Comment by sadick254** [comment]
There is a PR to revert the commit https://github.com/atom/atom/pull/21910.
